// Data for our PlatinumWheelz
const cars = [
    {
        id: "car_1",
        make: "Porsche",
        model: "911 GT3 RS",
        year: 2023,
        price: 245000,
        category: "Sport",
        mileage: 2012,
        image: "https://images.unsplash.com/photo-1503376760366-50e9ebf6d149?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true,
        specs: {
            horsepower: "518 hp",
            "0_60": "3.0",
            top_speed: "296 km/h",
            engine_size: "4.0L Flat-6",
            torque: "465 Nm",
            zero_to_100: "3.2s",
            fuel_consumption: "8.4 km/L",
            fuel_type: "Premium Unleaded",
            tank_capacity: "64 L",
            transmission: "7-Speed PDK Dual-Clutch",
            drivetrain: "RWD",
            airbags: "8 (Front, Side, Curtain, Knee)",
            abs: "Yes",
            esc: "Yes",
            driver_assist: "Lane Assist, Adaptive Cruise Control",
            crash_rating: "5-Star Euro NCAP",
            seating: "2",
            trunk_space: "132 L",
            wheelbase: "2,457 mm",
            ground_clearance: "100 mm",
            infotainment: "10.9\" PCM Touchscreen",
            carplay_android: "Apple CarPlay / Android Auto",
            sound_system: "Bose Surround Sound",
            keyless: "Yes",
            parking_sensors: "Front & Rear with Camera",
            reliability: "Above Average (J.D. Power)",
            spare_parts: "Widely Available",
            service_interval: "20,000 km / 12 months",
            warranty: "4 Years / 80,000 km"
        }
    },
    {
        id: "car_2",
        make: "Mercedes-Benz",
        model: "G-Class G63 AMG",
        year: 2024,
        price: 185000,
        category: "SUV",
        mileage: 724,
        image: "https://images.unsplash.com/photo-1520031441872-265e4ff70366?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true,
        specs: {
            horsepower: "577 hp",
            "0_60": "4.5",
            top_speed: "220 km/h",
            engine_size: "4.0L V8 Bi-Turbo",
            torque: "850 Nm",
            zero_to_100: "4.5s",
            fuel_consumption: "7.2 km/L",
            fuel_type: "Premium Unleaded",
            tank_capacity: "100 L",
            transmission: "9-Speed Automatic (9G-TRONIC)",
            drivetrain: "AWD",
            airbags: "9 (Front, Side, Curtain, Knee, Pelvic)",
            abs: "Yes",
            esc: "Yes",
            driver_assist: "Active Brake Assist, Blind Spot Assist, 360° Camera",
            crash_rating: "5-Star Euro NCAP",
            seating: "5",
            trunk_space: "667 L",
            wheelbase: "2,890 mm",
            ground_clearance: "241 mm",
            infotainment: "12.3\" MBUX Dual Screen",
            carplay_android: "Apple CarPlay / Android Auto",
            sound_system: "Burmester 3D Surround",
            keyless: "Yes",
            parking_sensors: "360° Camera with Parking Pilot",
            reliability: "Average (J.D. Power)",
            spare_parts: "Widely Available",
            service_interval: "25,000 km / 12 months",
            warranty: "4 Years / 80,000 km"
        }
    },
    {
        id: "car_3",
        make: "Audi",
        model: "RS e-tron GT",
        year: 2024,
        price: 148000,
        category: "Electric",
        mileage: 1287,
        image: "https://images.unsplash.com/photo-1614200187524-dc4b892acf16?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: true,
        specs: {
            horsepower: "637 hp",
            "0_60": "3.1",
            top_speed: "250 km/h",
            engine_size: "Dual Electric Motors",
            torque: "830 Nm",
            zero_to_100: "3.3s",
            fuel_consumption: "5.3 km/kWh",
            fuel_type: "Electric",
            tank_capacity: "93.4 kWh Battery",
            transmission: "2-Speed Automatic (Rear Axle)",
            drivetrain: "AWD (quattro)",
            airbags: "10 (Front, Side, Curtain, Knee, Center)",
            abs: "Yes",
            esc: "Yes",
            driver_assist: "Adaptive Cruise, Lane Keep, Pre Sense 360°",
            crash_rating: "5-Star Euro NCAP",
            seating: "4",
            trunk_space: "405 L (Front + Rear)",
            wheelbase: "2,900 mm",
            ground_clearance: "133 mm",
            infotainment: "10.1\" MMI Touchscreen + 12.3\" Virtual Cockpit",
            carplay_android: "Apple CarPlay / Android Auto",
            sound_system: "Bang & Olufsen 3D Premium",
            keyless: "Yes",
            parking_sensors: "Front & Rear with 360° Camera",
            reliability: "Above Average (Consumer Reports)",
            spare_parts: "Widely Available",
            service_interval: "30,000 km / 24 months",
            warranty: "4 Years / 80,000 km + 8 Years Battery"
        }
    },
    {
        id: "car_4",
        make: "Lamborghini",
        model: "Huracán EVO",
        year: 2023,
        price: 290000,
        category: "Supercar",
        mileage: 5150,
        image: "https://images.unsplash.com/photo-1544607145-6617ba3a35ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false,
        specs: {
            horsepower: "631 hp",
            "0_60": "2.9",
            top_speed: "325 km/h",
            engine_size: "5.2L V10 Naturally Aspirated",
            torque: "600 Nm",
            zero_to_100: "2.9s",
            fuel_consumption: "7.0 km/L",
            fuel_type: "Premium Unleaded",
            tank_capacity: "83 L",
            transmission: "7-Speed LDF Dual-Clutch",
            drivetrain: "AWD",
            airbags: "6 (Front, Side, Curtain)",
            abs: "Yes",
            esc: "Yes (LDVI System)",
            driver_assist: "Rear-view Camera, Park Assist",
            crash_rating: "Not Rated",
            seating: "2",
            trunk_space: "100 L",
            wheelbase: "2,620 mm",
            ground_clearance: "116 mm",
            infotainment: "8.4\" HMI Touchscreen",
            carplay_android: "Apple CarPlay / Android Auto",
            sound_system: "Sensonum Sound System",
            keyless: "Yes",
            parking_sensors: "Rear Sensors with Camera",
            reliability: "Average (Limited Data)",
            spare_parts: "Available via Dealer Network",
            service_interval: "15,000 km / 12 months",
            warranty: "3 Years / Unlimited km"
        }
    },
    {
        id: "car_5",
        make: "BMW",
        model: "M8 Competition",
        year: 2024,
        price: 140000,
        category: "Coupe",
        mileage: 8207,
        image: "https://images.unsplash.com/photo-1555353540-64fd8b016258?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false,
        specs: {
            horsepower: "617 hp",
            "0_60": "3.0",
            top_speed: "306 km/h",
            engine_size: "4.4L V8 Twin-Turbo",
            torque: "750 Nm",
            zero_to_100: "3.2s",
            fuel_consumption: "8.8 km/L",
            fuel_type: "Premium Unleaded",
            tank_capacity: "68 L",
            transmission: "8-Speed M Steptronic Automatic",
            drivetrain: "AWD (M xDrive)",
            airbags: "8 (Front, Side, Curtain, Knee)",
            abs: "Yes",
            esc: "Yes (M Dynamic Mode)",
            driver_assist: "Active Cruise, Lane Departure, Collision Warning",
            crash_rating: "5-Star Euro NCAP",
            seating: "4",
            trunk_space: "440 L",
            wheelbase: "2,822 mm",
            ground_clearance: "114 mm",
            infotainment: "12.3\" iDrive Touchscreen + 12.3\" Digital Cluster",
            carplay_android: "Apple CarPlay / Android Auto",
            sound_system: "Harman Kardon Surround",
            keyless: "Yes",
            parking_sensors: "Front & Rear with Surround View",
            reliability: "Above Average (J.D. Power)",
            spare_parts: "Widely Available",
            service_interval: "16,000 km / 12 months",
            warranty: "4 Years / 80,000 km"
        }
    },
    {
        id: "car_6",
        make: "Land Rover",
        model: "Range Rover SV",
        year: 2024,
        price: 220000,
        category: "SUV",
        mileage: 241,
        image: "https://images.unsplash.com/photo-1606016159991-d28bba2e43f5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
        featured: false,
        specs: {
            horsepower: "606 hp",
            "0_60": "4.3",
            top_speed: "261 km/h",
            engine_size: "4.4L V8 Twin-Turbo",
            torque: "750 Nm",
            zero_to_100: "4.5s",
            fuel_consumption: "8.0 km/L",
            fuel_type: "Premium Unleaded",
            tank_capacity: "90 L",
            transmission: "8-Speed ZF Automatic",
            drivetrain: "AWD (Terrain Response 2)",
            airbags: "8 (Front, Side, Curtain, Knee)",
            abs: "Yes",
            esc: "Yes",
            driver_assist: "Adaptive Cruise, Blind Spot, 3D Surround Camera",
            crash_rating: "5-Star Euro NCAP",
            seating: "4 (SV Configuration)",
            trunk_space: "725 L",
            wheelbase: "3,075 mm",
            ground_clearance: "295 mm",
            infotainment: "13.1\" Pivi Pro Touchscreen + 13.7\" Digital Cluster",
            carplay_android: "Apple CarPlay / Android Auto",
            sound_system: "Meridian Signature 3D Sound (1,600W)",
            keyless: "Yes",
            parking_sensors: "360° Parking Aid with ClearSight Camera",
            reliability: "Below Average (Consumer Reports)",
            spare_parts: "Available via Dealer Network",
            service_interval: "26,000 km / 24 months",
            warranty: "5 Years / 100,000 km"
        }
    }
];

// Helper to format currency
function formatCurrency(amount) {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        maximumFractionDigits: 0
    }).format(amount);
}
